package codex

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
)

// ProviderConfig is the non-secret information needed to render a codex config
// pointed at an Azure OpenAI-style provider. The key is never here: it is
// referenced by the name of the environment variable that holds it.
type ProviderConfig struct {
	// Model is the deployment/model the run defaults to (e.g. "gpt-5.4").
	Model string
	// BaseURL is the provider base URL, including the API path
	// (e.g. "https://<resource>.openai.azure.com/openai/v1").
	BaseURL string
	// EnvKey is the NAME of the environment variable holding the API key
	// (e.g. "SIMPLYCUBED_AZURE_OPENAI_API_KEY"). Never the value.
	EnvKey string
	// WireAPI is the codex wire protocol; defaults to "responses".
	WireAPI string
	// ProviderName is the human label for the provider; defaults to "Azure OpenAI".
	ProviderName string
}

// WriteConfig renders a codex config.toml into codexHome and returns its path.
// This is how the GitHub Actions runtime produces a config per job (see
// docs/setup.md): non-secret settings are written here, the key is referenced by
// name, and the whole CODEX_HOME is discarded when the job ends. Only the env-var
// NAME is written; the key value never touches the file.
func WriteConfig(codexHome string, p ProviderConfig) (string, error) {
	if p.Model == "" || p.BaseURL == "" || p.EnvKey == "" {
		return "", errors.New("codex: Model, BaseURL, and EnvKey are required")
	}
	wireAPI := p.WireAPI
	if wireAPI == "" {
		wireAPI = "responses"
	}
	name := p.ProviderName
	if name == "" {
		name = "Azure OpenAI"
	}
	if err := os.MkdirAll(codexHome, 0o755); err != nil {
		return "", err
	}
	body := fmt.Sprintf(`# Generated by SimplyCubed Code. Do not edit by hand; it is rendered per run.
# The API key is read from the %[4]s environment variable; only its name is here.
model = %[1]q
model_provider = "azure"

[model_providers.azure]
name = %[2]q
base_url = %[3]q
env_key = %[4]q
wire_api = %[5]q
`, p.Model, name, p.BaseURL, p.EnvKey, wireAPI)

	path := filepath.Join(codexHome, "config.toml")
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		return "", err
	}
	return path, nil
}
